Update main.yml

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -77,7 +77,14 @@ jobs:
         run: |
           source ~/.bashrc
           conda activate heart-attack-predictor
-          mlflow models build-docker --model-uri "runs:/$RUN_ID/model" --name "workflow-c"
+          # Print the RUN_ID for debugging
+          echo "Using RUN_ID: $RUN_ID"
+          # Check if the model artifacts exist
+          if [ ! -d "MLProject/mlruns/0/$RUN_ID/artifacts/model" ]; then
+          echo "Model not found for RUN_ID: $RUN_ID. Exiting."
+          exit 1
+          fi
+          mlflow models build-docker --model-uri "runs:/$RUN_ID/model" --name "workflow-ci"
           
       - name: Log in to Docker Hub
         uses: docker/login-action@v2
